### ISSUE TITLE
Mastodon.py uses blocking I/O operations

### ISSUE THREAD

**Issue by zhoreeq** [ChronosX88/mastodon-bridge-bot#4]
Бот построен на asyncio, но для мастодона используется синхронная либа Mastodon.py. В результате, программа выполняется в одном потоке и будет "зависать" каждый раз, когда Mastodon.py делает сетевые запросы.

Если что, есть асинхронная библиотека https://github.com/popura-network/atoot

**Comment by ChronosXYZ** [comment]
Thanks, I will refactor mastodon part in code using your library.

**Comment by ChronosXYZ** [comment]
Resolved in d5df81593e83858b4ef4903b139657c63e44cf11 and a761754c68eadb49bb6e4bc91d3f8e5ecf2a5870.
